/*
 * page.tsx — import sections here, no logic
 * Generated by /init-landing — each section is imported from src/sections/
 *
 * Example after generation:
 *   import Hero from "@/sections/Hero/Hero";
 *   import Features from "@/sections/Features/Features";
 *   ...
 *   export default function Home() {
 *     return <> <Hero /> <Features /> ... </>;
 *   }
 */

export default function Home() {
  return null;
}
